### PR TITLE
Various fixes

### LINKED ISSUE #225: XTerm takes a while to start up
An odd little issue I've run into with LeftWM.
For some reason, XTerm can take a while to start up, up to as long as 8 seconds in some cases.

This doesn't happen with anything else, just that.
For now I've been using Alacritty, but XTerm is my preferred terminal and I'd love to figure out what the issue is.

### LINKED ISSUE #585: IntelliJ autocomplete loses focus (Sloppy)
The autocomplete popup in IntelliJ makes the whole IDE lose focus if the mouse is hovered over the popup and then back out again.
autocomplete1

It's especially problematic when the mouse is already positioned where the popup will be rendered, because then it can just lose focus mid typing.

autocomplete2

**More information**
- If the mouse cursor never touches the autocomplete popup everything works as expected, accepting an option with <kbd>Enter</kbd> or <kbd>Tab</kbd> doesn't make the IDE lose focus.
- Everything works fine in the `ClickTo` focus behavior.

*I'm not sure how to get the xprops of the autocomplete popup, because if I change focus it gets destroyed* :upside_down_face:

### LINKED ISSUE #592: [feature] `SoftReload` should resore 'last focused workspace'
This is merely a tracking issue as this is created post fix simply to include it easily in the changelog for bump to `0.2.10`

### PR DESCRIPTION
**Pull request by AethanFoot**
Fixes #585, fixes #225 (happy accident), fixes #592, partial #560 (At least the steps found), partial #517. With #517 I feel that the issue with clickto specifically is (mostly) fixed, there are still times that we can freeze with the motion/resize and spam clicking and such. However if think these issues can be reproduced in other focusbehaviours with enough effort. In future we will want to optimise the events we read will in these modes to prevent them being "held up" by events less important to the user (e.g. visual responsiveness events), similar to what dwm does in their move/resize functions. This will be in the future though (especially as I currently don't have an idea of how to integrate it nicely into our structure).
Many Thanks!

### CODE REVIEW

**Comment by hertg** [comment]
I can confirm that this fixes #585.

**Comment by VuiMuich** [comment]
I think I can confirm fix for #560
not 100% sure though, as this one was kind of slippery while tracking down :wink:

**Comment by cecton** [comment]
@AethanFoot I love how you "accidentally" fixed #225 which is a huge deal for me :rofl: 

So I tested and did you fix it? My answer is: yes and no.

The very first run of xterm in the session takes a few seconds but clearly much less than the 6 seconds of the socket timeout there is without your fixes. The next instances of xterm in the session are instantaneous. If I quit all the active xterm in the session and start a new one, it is instantaneous too.

For me it's good enough we can close #225 with this fix. Thanks a LOT @AethanFoot I will finally be able to start using leftwm actively.

I understand some are curious about why am I so insistent on xterm. I don't like to talk about it because it's such an unpopular opinion I have that people are making fun of it. Though you've been all very nice and I feel okay to share this.

I know this sounds weird because there are better alternatives to xterm out there but I have a preference for xterm because of its standardiness, it's use of xfont without antialiasing and its absence of GPU acceleration. All the modern terminals out there focus on GPU performance and beautifulness. Unfortunately for me, unless I make one myself, there will be no other xterm.

**Comment by AethanFoot** [comment]
I found myself prefering st for its fast launching (compared to alacritty and such), and haven't found where it is noticeably slower in general use (also not fond of the idea of running a daemon constantly). And I can get it to look pretty (eventhough I had to fight it to get unicode and emojis to work completely). Im very into minimising without comprimisings looks (which is why I still use picom and lightdm, still 7 ish second system boot time).

**Comment by AethanFoot** [comment]
The soft locks I could produce was due to the pointer grabbing be sync rather than async with grab_buttons. The reason it was sync was to allow replay_click to be simple, with async the ReplayPointer doesn't work. This means a less elegant way has to be used which I currently don't know if it causes issues.

**Comment by hertg** [comment]
Just for my understanding: What does the replay-click do, why is it needed?

**Comment by AethanFoot** [comment]
replay_click is so the click continues to the application, e.g. if you click on an unfocused app the click will not just disappear (will do the action expected).

File: leftwm-core/src/display_servers/xlib_display_server/event_translate.rs [hunk 1]
```diff
@@ -100,6 +108,17 @@ fn from_map_request(raw_event: xlib::XEvent, xw: &mut XWrap) -> Option<DisplayEv
     if let Some(trans) = trans {
         w.transient = Some(WindowHandle::XlibHandle(trans));
     }
+    // Initialise the windows floating we the pre-mapped settings.
```
Comment (cecton) [inline leftwm-core/src/display_servers/xlib_display_server/event_translate.rs:111]: typo?
```suggestion
    // Initialise the windows floating with the pre-mapped settings.
```

File: leftwm-core/src/display_servers/xlib_display_server/xwrap/getters.rs [hunk 2]
```diff
@@ -160,6 +160,9 @@ impl XWrap {
             // Make sure that width and height are not smaller than the min values.
             xyhw.w = std::cmp::max(xyhw.w, xyhw.minw);
             xyhw.h = std::cmp::max(xyhw.h, xyhw.minh);
+            // Ignore the sizing if the sizing is set to 0.
+            xyhw.w = if xyhw.w == Some(0) { None } else { xyhw.w };
+            xyhw.h = if xyhw.h == Some(0) { None } else { xyhw.h };
```
Comment (cecton) [inline leftwm-core/src/display_servers/xlib_display_server/xwrap/getters.rs:165]:
```suggestion
            xyhw.w = xyhw.w.filter(|w| w != 0);
            xyhw.h = xyhw.h.filter(|h| h != 0);
```

File: leftwm-core/src/display_action.rs [hunk 3]
```diff
@@ -38,7 +38,7 @@ pub enum DisplayAction {
     DestroyedWindow(WindowHandle),
 
     /// Tell a window that it is to become focused.
-    WindowTakeFocus(Window),
+    WindowTakeFocus(Window, Option<WindowHandle>),
```
Comment (cecton) [inline leftwm-core/src/display_action.rs:41]: Not particularly fan of the tuple variant for this variant in particular because it is not obvious at all to understand what are the fields. I'd suggest converting to a struct variant:

```suggestion
    WindowTakeFocus {
        window: Window,
        previous_handle: WindowHandle,
    },
```

**Comment by AethanFoot** [comment]
Will intergrate those changes properly when back on my desktop.

**Comment by VuiMuich** [comment]
I just found a tiny issue:
when you issue the `SoftReload` from any tag other then the first, the windows on the first tag have no focus (focus mode `Driven, assume `ClickTo` might be affected as well).
Any action to enforce a focus on this tag like summoning a scratchpad or opening a new window, helps to catch these windows.
On the other hand, attempts to move focus or windows, detaches the windows from leftwm completely.

My guess is, that restoring the previous state somehow forces focus to the previously focused window on the focused tag, so either of these solutions should work:
- enforce focus loss and proper refocus in `SoftReload`
- restore focused tag in `SoftReload` (this one would probably nicer for the user eventually)

File: leftwm-core/src/display_servers/xlib_display_server/xwrap/mouse.rs [hunk 4]
```diff
@@ -1,25 +1,52 @@
...
     /// Grabs the mouse clicks of a window.
-    pub fn grab_mouse_clicks(&self, handle: xlib::Window) {
+    pub fn grab_mouse_clicks(&self, handle: xlib::Window, is_focused: bool) {
         self.ungrab_buttons(handle);
-        self.grab_buttons(handle, xlib::Button1, self.mouse_key_mask);
-        self.grab_buttons(handle, xlib::Button1, self.mouse_key_mask | xlib::ShiftMask);
-        self.grab_buttons(handle, xlib::Button3, self.mouse_key_mask);
-        self.grab_buttons(handle, xlib::Button3, self.mouse_key_mask | xlib::ShiftMask);
+        if !is_focused {
+            self.grab_buttons(handle, xlib::Button1, xlib::AnyModifier, xlib::GrabModeSync);
```
Comment (hertg) [inline leftwm-core/src/display_servers/xlib_display_server/xwrap/mouse.rs:13]: i love this, now I can resize unfocused windows in `ClickTo` without left-clicking them first :)

File: leftwm-core/src/display_servers/xlib_display_server/xwrap/window.rs [hunk 5]
```diff
@@ -63,8 +63,9 @@ impl XWrap {
                     let _ = self.move_cursor_to_window(handle);
                 }
                 if self.focus_behaviour == FocusBehaviour::ClickTo {
-                    self.ungrab_buttons(handle);
-                    self.grab_buttons(handle, xlib::Button1, xlib::AnyModifier);
+                    // self.ungrab_buttons(handle);
+                    // self.grab_buttons(handle, xlib::Button1, xlib::AnyModifier);
```
Comment (hertg) [inline leftwm-core/src/display_servers/xlib_display_server/xwrap/window.rs:67]:
```suggestion

```

**Review by hertg — APPROVED** [review]

**Comment by hertg** [comment]
nice, this fixes the sizing issue I had with dialog boxes in NetExtender :)

**Comment by AethanFoot** [comment]
SoftReload now restores the last tag on a workspace (if it still exists) then focuses the last focused window on that tag.
Thanks!

**Comment by VuiMuich** [comment]
fixes #592 :grin:

**Comment by AethanFoot** [comment]
Ok I feel I have gone a far as I can in this pr. If you treat it nicely it should not break :worried:. 
Thanks.

**Comment by VuiMuich** [comment]
Aethan SneakyPete Rocket trying to silently adding WM_CLASS, just after stating 'this pr is done'. 
But I caught you red handed!

Nicely done, though!!! 🥳

**Comment by hertg** [comment]
I think we can merge this. Or is there anything missing? 
I'm looking forward to having this in the main branch, and to finally get my dev-branch to include those fixes :stuck_out_tongue_closed_eyes:
