### PR TITLE
Improve dialog handling & Optimise motion limiting & More fixes to come

### LINKED ISSUE #497: Intellij/Brave pop-up exits fullscreen mode
**Describe the bug**
Another thing with Intellij/Brave ;) When I'm in fullscreen mode inside intellij or Brave a new popup is forcing leftwm to enter the tile mode.
Pop-up is kind of Dialog window so it's not tiled. It happens with one intellij/brave on workspace as well with multiple. 

**To Reproduce**
1. Open Intellij/Brave
2. Get into leftwm's Full screen mode
3. Trigger any pop-up (File/Settings)(Brave -> r click save link as)
4. Intellij/Brave returns to tile mode(error)

**Expected behavior**
I tested it with other application like Slack and their pop-ups doesn't change the mode.

**Environment:**
 - ArcoLinux
 - Output of `leftwm-check`
 ```
:: LeftWM version: 0.2.9
:: LeftWM git hash: 6d635d1-modified
:: Loading configuration . . .
    -> Configuration loaded OK
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK
:: Checking theme . . .
    -> Theme OK
```
 
 Is it expected behaviour?

### LINKED ISSUE #574: Floating dialogues smaller than expected
**Describe the bug**
Floating dialogues popped up by programs are smaller than normal.

**To Reproduce**
1. start gimp and open any image.
2. Click on 'colors'->'desaturate'->'desaturate'
3. the floating dialogue is smaller and some options are hidden. It can be enlarged by mod+mouse right drag, but need to do it every time.

**Expected behavior**
The size of floating windows should have a sane default to display everything in the diagloue.

**Screenshots**

**Environment:**
 - OS/Distro:  arch
 - Output of `leftwm-check`
x leftwm-check
:: LeftWM version: 0.2.10
:: LeftWM git hash: 26cc711
:: Loading configuration . . .
    -> Configuration loaded OK
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK
:: Checking theme . . .
    -> Theme OK

**Additional context**
wrong dialogue
pic-window-211111-1301-27

correct dialogue
pic-window-211111-1301-50

### PR DESCRIPTION
**Pull request by AethanFoot**
This has improved the dialog handling in making sure the window size better for apps using depreciated things (e.g. jetbrains), and made dialogs spawn more centered (e.g. non-resizable dialogs will now spawn centered on the workspace). I will add some other small bugs fixes in here, if you have any let me know.

This now has an automatic way of getting refresh rate with xrandr. And the limit is moved to event_translate to optimise a bit, as instead of mostly processing an event then ignoring it we ignored as soon as it comes in.

Fixes #497, fixes #574. I have also removed an issue where a fullscreen window's drop down menus would be buggy, by removing the move to top for fullscreen windows. This also allows child dialogs and such to appear above the fullscreen window easier (without also being buggy). This however has the issue of windows which have override redirect set to true (we completely ignore these windows) may appear over the fullscreen window, e.g. the polybar window tray often has override redirect set to true. I prefer these windows appearing above compared to the apps being buggy and slow to response (To 100% clarify the bugginess is due to the constant move to top).

The issues with unmanaged window appearing above fullscreen windows is now fixed.

Thanks!

### CODE REVIEW

**Comment by lkadalski** [comment]
I've just checked it out. It's more than good, it's excellent :+1: 
Child windows are now in good position and in expected size. 
This fixes #497 in Intellij and Brave. :rocket:

File: leftwm-core/src/display_servers/xlib_display_server/mod.rs [hunk 1]
```diff
@@ -175,22 +174,50 @@ impl DisplayServer for XlibDisplayServer {
...
+                    fullscreen_windows.iter().map(|w| w.handle).collect();
+                let (fullscreen_children, other): (Vec<&Window>, Vec<&Window>) =
+                    other.iter().partition(|w| {
+                        level2.contains(&w.transient.unwrap_or(WindowHandle::XlibHandle(0)))
+                    });
+                // Fullscreen windows children.
+                let level1: Vec<WindowHandle> =
+                    fullscreen_children.iter().map(|w| w.handle).collect();
+
+                log::info!("Children: {:?}", level1);
```
Comment (lkadalski) [inline leftwm-core/src/display_servers/xlib_display_server/mod.rs:193]: Do we need such `info` logs in master? Maybe it should be `debug!` ?

**Review by lkadalski — APPROVED** [review]
Clean changes and explanatory comments. :+1:

File: leftwm-core/src/display_servers/xlib_display_server/mod.rs (hunk 1 above)
Comment (AethanFoot) [reply leftwm-core/src/display_servers/xlib_display_server/mod.rs]: Forgot to remove them.

File: leftwm-core/src/handlers/window_handler.rs [hunk 2]
```diff
@@ -262,59 +279,68 @@ fn setup_window(
...
+                DisplayAction::SetState(fsw.handle, !fsw.is_fullscreen(), WindowState::Fullscreen);
+            state.actions.push_back(act);
+            was_fullscreen = true;
+        }
+        if matches!(layout, Layout::Monocle | Layout::MainAndDeck) {
+            // Extract the current windows on the same workspace.
+            let mut to_reorder = helpers::vec_extract(&mut state.windows, for_active_workspace);
+            if layout == Layout::Monocle || to_reorder.is_empty() {
+                // When in monocle we want the new window to be fullscreen if a window was
+                // fullscreen.
```
Comment (hertg) [inline leftwm-core/src/handlers/window_handler.rs:302]: I love those comments, now even I can understand what that code does :P

File: leftwm-core/src/models/tag.rs [hunk 3]
```diff
@@ -242,18 +242,30 @@ impl Tag {
...
-            w.set_visible(true);
+            window.set_visible(true);
+            window.normal = workspace.xyhw;
+            let handle = window.handle;
+            windows
+                .iter_mut()
+                .filter(|w| {
+                    w.has_tag(&self.id)
+                        && w.transient.unwrap_or(WindowHandle::XlibHandle(0)) == handle
+                        && !w.is_unmanaged()
```
Comment (hertg) [inline leftwm-core/src/models/tag.rs:257]: I know it's kinda dumb, but I recently thought about adding a `window.is_managed()` method which just runs `!self.is_unmanaged()` internally. Because I found myself tripping up on the double negation of `!w.is_unmanaged()` more than once :laughing:

Comment (hertg) [reply leftwm-core/src/models/tag.rs:257]: We'd better address this minor QoL improvement in another PR though, I'd rather get this here merged as soon as possible :)

**Review by hertg — APPROVED** [review]
I'm so stoked to get this one merged, it seems like it addresses a lot of bugs and increases the overall quality of the WM.
I don't have anything to say about the code really, all my comments are just hinting typos and stuff. Fix the ones you agree with and ignore the ones you don't. I'm happy if it gets merged as it is.
Thank you so much for the work! :heart:

**Comment by AethanFoot** [comment]
Ill resolve those little bits tomorrow morning, once I have done that shall I merge?

**Comment by hertg** [comment]
> Ill resolve those little bits tomorrow morning, once I have done that I will merge.

yeah definitely! :)
