### PR TITLE
FIX: make leftwm-check -m migrate scratchpads correctly

### LINKED ISSUE #860: leftwm-check -m dont migrate scratchpads correctly
### Describe the bug

Migrating from config.toml to config.ron handle scratchpad elements incorrect

### Expected behavior (optional)

Having the following config.toml structure:
```
scratchpad = [
    { name = "Mousepad", value = "mousepad", x = 200, y = 300, height = 600, width = 800 },
]
```
and the running `leftwm-check -m` will generate this block in the config.ron file:
```
    scratchpad: [
        (name: ("Mousepad"), value: "mousepad", x: 200, y: 300, height: 600, width: 800),
    ],
```
Simply removing the tuple definition for name will fix the problem

### Steps to reproduce (optional)

_No response_

### Relevant log output (optional)

_No response_

### OS / Distro

Manjaro 22.0.0

### Additional System Information (optional)

_No response_

### LeftWM Check

```text
leftwm-check
:: LeftWM version: 0.3.0
:: LeftWM git hash: d4fae27
:: Loading configuration . . .
    -> Configuration loaded OK
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK
:: Checking theme . . .
WARN: TOML as config format is about to be deprecated.
      Please consider migrating to RON or contact the theme creator about this topic.
      Note: make sure the `up` script is loading the correct theme file.
ERROR: File not found: theme.ron
```

### PR DESCRIPTION
**Pull request by SamClercky**
# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

The newtype `ScratchPadName` did not define a way to convert to `String` (only from `String` to `ScratchPadName`). This gave the problem that the migration of `TOML` to `RON` introduced extra `(` and `)` around the scratchpad name and thus generating a bad config.

This PR also adds a test which tests that the (de)serialization can go in 2 ways. To make the test initially fail, a default scratchpad config was added to the `Default` impl of `Config`. The parameters were taken from the LeftWM wiki.

Fixes #860

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Updated user documentation:

Please insert user documentation that should be updated (as in the wiki).

See [CONTRIBUTING.md User Documentation section](../CONTRIBUTING.md#user-documentation) for further details.

**Note: Manual page changes must be performed in a commit, not in this PR section.**

# Checklist:

- [x] Ran `make test-full` locally with no errors or warnings reported
- [x] Manual page has been updated accordingly
- [x] Wiki pages have been updated accordingly (to perform **after** merge)

### CODE REVIEW

File: leftwm/src/config/default.rs [hunk 1]
```diff
@@ -199,14 +201,23 @@ impl Default for Config {
...
+            width: Some(Size::Pixel(200)),
+        };
+
         Self {
             workspaces: Some(vec![]),
             tags: Some(tags),
             layouts: LAYOUTS.to_vec(),
             layout_mode: LayoutMode::Workspace,
             // TODO: add sane default for scratchpad config.
             // Currently default values are set in sane_dimension fn.
```
Comment (TornaxO7) [inline leftwm/src/config/default.rs:219]: Is this TODO still needed?

**Review by TornaxO7 — COMMENTED** [review]
Added a little question.

File: leftwm/src/config/default.rs (hunk 1 above)
Comment (VuiMuich) [inline leftwm/src/config/default.rs:219]: I think what was meant by this TODO was that `fn sane_dimension` is not a good place to set some default values.
Maybe we can clean this up with a fix to #856?

Good catch though.

Comment (SamClercky) [reply leftwm/src/config/default.rs:219]: Good question. I don't really know as this looks to me more like the question of what the defaults should be. I added these values because these came from the wiki and gave a case to test against.

This might create the need to open a new PR which discusses what the defaults should look like?

**Comment by VuiMuich** [comment]
Thanks for the quick fix @SamClercky. 
LGTM

:heart: for the two-in-one test :smiley:

File: leftwm/src/config/default.rs (hunk 1 above)
Comment (TornaxO7) [reply leftwm/src/config/default.rs:219]: > This might create the need to open a new PR which discusses what the defaults should look like?

I agree

**Review by TornaxO7 — APPROVED** [review]
