### PR TITLE
fix #801

### LINKED ISSUE #801: Session closes when performing a SoftReload
**Describe the bug**
When performing a `SoftReload`, instead of reloading Leftwm, it closes the session and it sends you to the login manager (Lightdm in my case),  and so closing all the programs

**To Reproduce**
Just soft reload with either `leftwm command SoftReload` or `$MOD + Shift + R`

**Expected behavior**
It shouldn't close the session ;-;

**Environment:**
 - OS/Distro: I use Artix Linux btw
 - Output of `leftwm-check`
 ```:: LeftWM version: 0.3.0
:: LeftWM git hash: cc5b1b1
:: Loading configuration . . .
    -> Configuration loaded OK 
:: Checking keybinds . . .
    -> All keybinds OK
:: Checking environment . . .
    -> Environment OK 
:: Checking theme . . .
    -> Theme OK 
```

**Additional context**
It got fixed by downgrading to `8912c25`, so it may be related to either [this](https://github.com/leftwm/leftwm/pull/798) or [this](https://github.com/leftwm/leftwm/pull/788)

### PR DESCRIPTION
**Pull request by VuiMuich**
# Description

The earlier refactors missed to preserve an important `loop` that is needed for leftwm to restart the `worker` after being killed during a `SoftReload`
Fixes #801

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Updated user documentation:

(not applicable)

# Checklist:

- [x] Ran `make test-full` locally with no errors or warnings reported
- [ ] Manual page has been updated accordingly
- [ ] Wiki pages have been updated accordingly (to perform **after** merge)

### CODE REVIEW

File: leftwm/src/bin/leftwm.rs [hunk 1]
```diff
@@ -133,28 +133,30 @@ fn start_leftwm() {
...
-        // remove all child processes which finished
-        children.remove_finished_children();
-
-        while is_suspending(&flag) {
-            nix::unistd::pause();
+    loop {
+        // Boot everything WM agnostic or LeftWM related in ~/.config/autostart
+        let mut children = Nanny::autostart();
+
+        let flag = get_sigchld_flag();
```
Comment (AethanFoot) [inline leftwm/src/bin/leftwm.rs:140]: loop should start after here, as the children and flag dont need resetting

Comment (VuiMuich) [reply leftwm/src/bin/leftwm.rs]: Thanks.
